site_name: PyTestArch

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
      extra:
        version:
          provider: mike
  - search

nav:
  - index.md
  - details.md
  - changelog.md
  - Reference:
      - references/general.md
      - references/query_language.md
      - references/eval_structure.md
      - references/eval_structure_generation.md
      - references/diagram_extension.md
      - references/rule_assessment.md



repo_url: https://github.com/zyskarch/pytestarch