site_name: PyTestArch

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
extra:
  version:
    provider: mike


nav:
  - Home: 'index.md'
  - Features:
      - 'General Concept': 'features/general.md'
      - 'Module Dependency Rules': 'features/module_import_checks.md'
      - 'Layer Architecture Dependency Rules': 'features/layer_architecture_checks.md'
      - 'Module Dependency Rule Generation from PlantUML Component Diagrams': 'features/plantuml.md'
      - 'Visualization': 'features/visualization.md'
  - Changelog: 'changelog.md'
  - Reference:
      - references/general.md
      - references/query_language.md
      - references/eval_structure.md
      - references/eval_structure_generation.md
      - references/diagram_extension.md
      - references/rule_assessment.md



repo_url: https://github.com/zyskarch/pytestarch