name: Tests
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        poetry-version: [2.1.3]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Setup a local virtual environment
        run: |
            poetry config virtualenvs.create true --local
            poetry config virtualenvs.in-project true --local
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
            path: ./.venv
            key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: install dependencies
        run: poetry install --extras visualization
      - name: pytest
        run: poetry run pytest